version: "3.8"

services:
  app:
    container_name: eat_it_app
    build:
      dockerfile: Dockerfile.development
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  postgres:
    container_name: eat_it_postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  bundle:
